name: groccery_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  bloc: ^8.1.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  freezed_annotation: ^2.4.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  assets:
   - assets/G.jpg
   - assets/G.png
   - assets/apple.jpg
   - assets/banana.webp
   - assets/bread.webp
   - assets/cb.webp
   - assets/cheese.webp
   - assets/egg.webp
   - assets/milk.webp
   - assets/pasta.webp
   - assets/rice.webp
   - assets/tomato.webp

